services:
  database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - db
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    environment:
      - DB_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - DB_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - PORT=${BACKEND_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DB_URI=mongodb://database:27017
      - DB_NAME=${DB_NAME}
      - CORS_ORIGIN=${VITE_BASE_URL}
      - NODE_ENV=production
    depends_on:
      - database
    networks:
      - db
      - app
    ports:
      - ${BACKEND_PORT}:3000

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_NODE_ENV=production
    depends_on:
      - api
    networks:
      - app
    ports:
      - ${FRONTEND_PORT}:80

networks:
  db:
  app:

volumes:
  mongo-data:
