services:
  mongodb:
    image: mongo
    restart: always
    ports:
        - "27017:27017"
    networks:
      - app
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    working_dir: /
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - app
    ports:
      - 3000:3000
    command: [sh, -c, "npm run start:dev"]
    volumes:
      - ./backend:/app

networks:
  app:

volumes:
  backend: