services:
  database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - db
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    environment:
      - DB_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - DB_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - PORT=${BACKEND_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DB_URI=mongodb://database:27017
      - DB_NAME=${DB_NAME}
      - CORS_ORIGIN=${VITE_BASE_URL}
      - NODE_ENV=developpement
    depends_on:
      - database
    ports:
      - ${BACKEND_PORT}:3000
    networks:
      - db
      - app
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - ./backend:/app
      - /app/node_modules

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - app
    ports:
      -  ${FRONTEND_PORT}:5173
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  db:
  app:

volumes:
  backend:
  frontend:
  mongo-data:
