services:
  database:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - db
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    environment:
      - DB_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - DB_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - PORT=${BACKEND_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DB_URI='mongodb://database:27017'
      - DB_NAME=${DB_NAME}
      - CORS_ORIGIN='http://web:5173'
      - NODE_ENV=developpement

    depends_on:
      - database
    networks:
      - db
      - app
    ports:
      - 3000:${BACKEND_PORT}
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - ./backend:/app

networks:
  db:
  app:

volumes:
  backend:
  mongo-data:
